---
  - name: ans_10
    hosts: stage_1
    roles: 
      - role: nginx_deploy
        tags: nginx
      - role: vhost_deploy
        tags: vhost
      
    
 
       
        
     
     
       
    