---
  - name: install Nginx at DO
    hosts: stage_1
    vars: 
      source_folder_files: /mnt/e/rebrain/ansible/1/files
      source_folder_templates: /mnt/e/rebrain/ansible/1/template
      destin_folder_site: /var/www/html
      destin_folder_conf: /etc/nginx/sites-available
      enabled:  /etc/nginx/sites-enabled/

    tasks:
 
     - name: Install package nginx
       apt: 
        name: nginx=1.14.0-0ubuntu1.9
        update_cache: yes 
        state: present
       notify:  
         - Starting service nginx

     - name: make sites dir
       ansible.builtin.file: 
        path: "{{ item }}"
        state: directory
        mode: '0755'
       loop: 
           - "{{ destin_folder_site }}/v1"
           - "{{ destin_folder_site }}/v2"
     
     - name: copy files
       copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
       loop:
          - { src: "{{ source_folder_files }}/v1_index.html", dest: "{{ destin_folder_site }}/v1/index.html" }
          - { src: "{{ source_folder_files }}/v2_index.html", dest: "{{ destin_folder_site }}/v2/index.html" }  
          - { src: "{{ source_folder_files }}/nginx.conf", dest: "/etc/nginx" }
       notify:  
         - Reload service nginx
        
     - name: generating configs
       template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: "{{ item.mode }}"
       with_items:
             -  { src: "{{ source_folder_templates }}/v1.conf.j2" , dest: "{{ destin_folder_conf }}/v1.conf", mode: "644"}
             -  { src: "{{ source_folder_templates }}/v2.conf.j2" , dest: "{{ destin_folder_conf }}/v2.conf", mode: "644"}  
       notify:  
         - Reload service nginx    

     - name: make a simlink
       ansible.builtin.file:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         owner: root
         group: root
         state: link
       loop:
           - { src: "{{ destin_folder_conf }}/v1.conf", dest: "{{ enabled }}/v1.conf" }
           - { src: "{{ destin_folder_conf }}/v2.conf", dest: "{{ enabled }}/v2.conf" } 
          
       
    handlers: 
     - name: Starting service nginx
       service: 
         name: nginx
         state: started
         enabled: yes
     - name: Reload service nginx
       service: 
        name: nginx
        state: reloaded
       
    