---
# tasks file for loadbalancer
  - name: generating  nginx config
    template:
          src: "nginx.conf.j2"
          dest: "{{ main_nginx_folder }}/nginx.conf"
          mode: 0644
    notify:  
       - Reload service nginx   