---
# tasks file for vhost_deploy
  - name: make sites dir
    file: 
       path: "{{ item }}"
       state: directory
       mode: '0755'
       recurse: yes
    loop: 
         - "{{ destin_folder_site }}/v1"
         - "/etc/letsencrypt/live/{{ server_name }}"
       
  - name: copy files
    copy: 
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
    loop:
        - { src: "v1_index.html", dest: "{{ destin_folder_site }}/v1/index.html" }
        - { src: "fullchain.pem", dest: "/etc/letsencrypt/live/{{ server_name }}/fullchain.pem" }
        - { src: "privkey.pem", dest: "/etc/letsencrypt/live/{{ server_name }}/privkey.pem" }
        - { src: "task10", dest: "~/.ssh/task10" }
    notify:  
       - Reload service nginx      

  - name: Generate dhparams
    shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
    args:
      creates: /etc/nginx/dhparams.pem   

  - name: generating  vhost's configs
    template:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          mode: "{{ item.mode }}"
    with_items:
           -  { src: "v1.conf.j2" , dest: "{{ destin_folder_conf }}/v1.conf", mode: "644", server_name: "{{ server_name[0] }}", port: "{{ port[0] }}", webserver: "{{ webserver[0] }}"}
         
    notify:  
       - Reload service nginx    

  - name: make a simlink
    file:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
       owner: root
       group: root
       state: link
    loop:
         - { src: "{{ destin_folder_conf }}/v1.conf", dest: "{{ enabled }}/v1.conf" }
    
    notify:  
       - Reload service nginx   

     
       
      
       