---
# handlers file for loadbalancer
  - name: Starting service nginx
    service: 
         name: nginx
         state: started
         enabled: yes
  - name: Reload service nginx
    service: 
        name: nginx
        state: reloaded